### ISSUE TITLE
Is there a way to remove the background and only have a transparent background for OBS

### ISSUE THREAD

**Issue by Anthonybcit** [PunyFlash/Bongo-Cat#1]
Title^
i know im pretty late i just dont like having that giant colored square surrounding the cat

**Comment by punyflash** [comment]
You should use chroma key. For example:
1) Set your background as green
![image](https://user-images.githubusercontent.com/14828695/52500442-af98a600-2be6-11e9-8770-84218946b30e.png)
2) Then capture the window in OBS and add filter to your source
![image](https://user-images.githubusercontent.com/14828695/52500781-73b21080-2be7-11e9-9d06-994472e2ab76.png)
![image](https://user-images.githubusercontent.com/14828695/52500824-86c4e080-2be7-11e9-92e5-36f8049b4454.png)
3) Then set filter settings to best view and you're done =)
![image](https://user-images.githubusercontent.com/14828695/52501035-05218280-2be8-11e9-839c-c0eded86c277.png)
